# docker-compose.yml
version: "3.7"

services:
  proxy:
    image: image.koompi.org/library/pingora-proxy-server:latest
    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certbot:/certbot
      - acme-challenge:/var/www/html/.well-known/acme-challenge
    environment:
      - SWARM_MODE=true
      - SWARM_NETWORKS=ingress
      - LOG_LEVEL=info
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s

volumes:
  certbot:
  acme-challenge:

networks:
  proxy-network:
    external: true
