# docker-compose.yml with enhanced security features
version: "3.7"

services:
  proxy:
    image: 192.168.1.109:80/library/pingora-proxy-server:latest
    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gluster/certbot:/certbot
      - /mnt/gluster/acme-challenge:/var/www/html/.well-known/acme-challenge
    environment:
      - SWARM_MODE=true
      - SWARM_NETWORKS=ingress
      - LOG_LEVEL=info
      - ENFORCE_NETWORK_ISOLATION=true
      # - DEFAULT_MEMORY_LIMIT=512M
      # - DEFAULT_CPU_LIMIT=0.5
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 512M
      # Security configurations
      # These are applied to the container runtime
      config:
        - source: proxy-security-policy
          target: /etc/security-policy.json
          mode: 0440
    # Add security configurations
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges=true
      - userns=host
    read_only: true

networks:
  proxy-network:
    external: true
    driver_opts:
      encrypted: "true"

configs:
  proxy-security-policy:
    file: ./security-policy.json
