; Global options
foreground = yes
debug = 7
output = /dev/stdout

; Certificate/key configuration
cert = /certs/weteka-mongodb-67f532-9fac8609-0c996391.koompi.cloud/fullchain.pem
key = /certs/weteka-mongodb-67f532-9fac8609-0c996391.koompi.cloud/privkey.pem

; Service-level configuration for MongoDB
[mongodb-weteka]
accept = 0.0.0.0:27017
connect = tasks.weteka-mongodb-67f532-9fac8609:27017
protocol = tcp
sni = weteka-mongodb-67f532-9fac8609-0c996391.koompi.cloud

[mongodb-riverbase]
accept = 0.0.0.0:27018
connect = tasks.riverbase-mongodb-67f532-b404d4af:27017
protocol = tcp
sni = riverbase-mongodb-67f532-b404d4af-a211fcb5.koompi.cloud

; Add more MongoDB services as needed
