[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:pingora-proxy]
command=/app/entrypoint.sh
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=5
priority=10

[program:cert-manager]
command=/app/cert-manager.sh
stdout_logfile=/var/log/cert-manager.log
stderr_logfile=/var/log/cert-manager.log
autorestart=true
startretries=5
priority=20

[eventlistener:processes]
command=bash -c "echo READY && read line && echo PROCESSING && if [[ -f /pingora-proxy/cert_renewed ]]; then rm -f /pingora-proxy/cert_renewed && echo 'Sending SIGHUP to pingora-proxy'; supervisorctl signal HUP pingora-proxy; fi && echo RESULT 2 && echo OK"
events=PROCESS_STATE,TICK_60